spring:
  application:
    name: blackjack

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack

  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack?sslMode=DISABLED&allowPublicKeyRetrieval=true
    username: blackjack
    password: blackjack
    pool:
      enabled: true
      initial-size: 1
      max-size: 10
      validation-query: SELECT 1
      validation-depth: remote
      max-idle-time: 30s
      max-life-time: 30m

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/blackjack?allowPublicKeyRetrieval=true&useSSL=false
    user: blackjack
    password: blackjack

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    io.asyncer.r2dbc.mysql: DEBUG
    org.springframework.r2dbc: DEBUG
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ALWAYS

